import { Meta, StoryObj } from '@storybook/react-vite';
import { Modal } from './Modal.component';
declare const meta: Meta<typeof Modal>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const SimpleConfirmNonDestructiveAction: Story;
export declare const ConfirmDesctructiveActionLowRisk: Story;
export declare const ConfirmDesctructiveActionMediumRisk: Story;
export declare const ConfirmDestructiveActionHighRisk: Story;
export declare const SimpleConfirmDialogWithDisabledButtons: Story;
export declare const AutoFocusDialog: Story;
export declare const DefaultWithForm: Story;
export declare const LargeWithForm: Story;
export declare const XLWithForm: Story;
export declare const XXLWithForm: Story;
export declare const NonCloseable: Story;
export declare const CloseOnBackdropClick: Story;
export declare const DisabledCloseButton: Story;
export declare const CustomModalFooter: Story;
export declare const TestSelectInModal: Story;
export declare const TestComboBoxInModal: Story;
//# sourceMappingURL=Modal.stories.d.ts.map