# How to run it locally:
#  1. Install license-eye:
#     `brew install license-eye`
#  2. Run license-eye:
#     `license-eye --config .github/licenserc.yaml header check`

# REUSE-IgnoreStart
header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: [year] SAP SE or an SAP affiliate company and Juno contributors
      SPDX-License-Identifier: Apache-2.0
    pattern: |
      SPDX-FileCopyrightText: [0-9]+ SAP SE or an SAP affiliate company and Juno contributors
      SPDX-License-Identifier: Apache-2\.0
# REUSE-IgnoreEnd
  paths: # `paths` are the path list that will be checked
    - "apps/**/*.ts"
    - "packages/**/*.ts"
    - "apps/**/*.tsx"
    - "packages/**/*.tsx"
    - "apps/**/*.js"
    - "packages/**/*.js"
    - "apps/**/*.jsx"
    - "packages/**/*.jsx"

  paths-ignore:
    - "**/routeTree.gen.ts"
    - "**/mockServiceWorker.js"
    - "**/generated/**"
    
  comment: on-failure

  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    JSX:
      extensions:
        - ".jsx"
      comment_style_id: SlashAsterisk
