enableMirror: false

packageExtensions:
  styled-components@*:
    dependencies:
      babel-plugin-macros: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
