import { Meta, StoryObj } from '@storybook/react-vite';
import { Badge } from './';
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const WithDefaultIcon: Story;
export declare const WithChildren: Story;
export declare const WithAnyIcon: Story;
export declare const Info: Story;
export declare const InfoWithIcon: Story;
export declare const Success: Story;
export declare const SuccessWithIcon: Story;
export declare const Warning: Story;
export declare const WarningWithIcon: Story;
export declare const Danger: Story;
export declare const DangerWithIcon: Story;
export declare const Error: Story;
export declare const ErrorWithIcon: Story;
export declare const AsButton: Story;
export declare const AsButtonDisabled: Story;
export declare const AsLink: Story;
export declare const AsLinkDisabled: Story;
export declare const AsButtonInfo: Story;
export declare const AsButtonSuccess: Story;
export declare const AsButtonWarning: Story;
export declare const AsButtonDanger: Story;
export declare const AsButtonError: Story;
export declare const AsLinkInfo: Story;
export declare const AsLinkDanger: Story;
export declare const AsButtonWithIcon: Story;
//# sourceMappingURL=Badge.stories.d.ts.map