/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as AppsAppIdImport } from "./routes/apps.$appId.*"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const AppsAppIdRoute = AppsAppIdImport.update({
  id: "/apps/$appId/*",
  path: "/apps/$appId/*",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/apps/$appId/*": {
      id: "/apps/$appId/*"
      path: "/apps/$appId/*"
      fullPath: "/apps/$appId/*"
      preLoaderRoute: typeof AppsAppIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/apps/$appId/*": typeof AppsAppIdRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/apps/$appId/*": typeof AppsAppIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/apps/$appId/*": typeof AppsAppIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/apps/$appId/*"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/apps/$appId/*"
  id: "__root__" | "/" | "/apps/$appId/*"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsAppIdRoute: AppsAppIdRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/apps/$appId/*"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/apps/$appId/*": {
      "filePath": "apps.$appId.*.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
