/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ExtensionIdChar42RouteImport } from "./routes/$extensionId.*"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionIdChar42Route = ExtensionIdChar42RouteImport.update({
  id: "/$extensionId/*",
  path: "/$extensionId/*",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$extensionId/*": typeof ExtensionIdChar42Route
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$extensionId/*": typeof ExtensionIdChar42Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$extensionId/*": typeof ExtensionIdChar42Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/$extensionId/*"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$extensionId/*"
  id: "__root__" | "/" | "/$extensionId/*"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionIdChar42Route: typeof ExtensionIdChar42Route
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$extensionId/*": {
      id: "/$extensionId/*"
      path: "/$extensionId/*"
      fullPath: "/$extensionId/*"
      preLoaderRoute: typeof ExtensionIdChar42RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionIdChar42Route: ExtensionIdChar42Route,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
