import { default as React } from '../../../../../node_modules/.pnpm/react@19.3.0/node_modules/react';
import { TextInput } from './index';
import { Meta, StoryObj } from '@storybook/react-vite';
type TextInputProps = React.ComponentProps<typeof TextInput>;
declare const meta: Meta<TextInputProps>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const RequiredWithLabel: Story;
export declare const Invalid: Story;
export declare const Valid: Story;
export declare const Autofocus: Story;
export declare const Disabled: Story;
export declare const ReadOnly: Story;
export declare const Email: Story;
export declare const Tel: Story;
export declare const Url: Story;
export declare const Number: Story;
export declare const Password: Story;
export declare const WithHelpText: Story;
export declare const WithHelpTextAsNode: Story;
export declare const WithSuccessText: Story;
export declare const WithErrorText: Story;
//# sourceMappingURL=TextInput.stories.d.ts.map