/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as IndexRouteImport } from './routes/index'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/violations': typeof ViolationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/violations': typeof ViolationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/violations': typeof ViolationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/violations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/violations'
  id: '__root__' | '/' | '/violations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViolationsRoute: typeof ViolationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViolationsRoute: ViolationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
