import { Meta, StoryObj } from '@storybook/react-vite';
import { DateTimePicker } from './index';
declare const meta: Meta<typeof DateTimePicker>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const Required: Story;
export declare const Disabled: Story;
export declare const WithPlaceholder: Story;
export declare const WithValue: Story;
export declare const WithDefaultDate: Story;
export declare const WithDefaultHourAndMinute: Story;
export declare const WithDefaultValue: Story;
export declare const WithValueAsDateString: Story;
export declare const WithValueAsIsoDateString: Story;
export declare const WithValueAsTimestamp: Story;
export declare const WithValueAsTodayShortcut: Story;
export declare const WithCustomDateFormat: Story;
export declare const WithTime: Story;
export declare const WithTimeAndSeconds: Story;
export declare const WithTimeWithCustomHourIncrement: Story;
export declare const WithTimeWithCustomMinuteIncrement: Story;
export declare const With24hTime: Story;
export declare const ShowTwoMonths: Story;
export declare const WithWeekNumbers: Story;
export declare const WithShorthandCurrentMonth: Story;
export declare const WithMonthSelectorDropdown: Story;
export declare const AllowInput: Story;
export declare const Multiple: Story;
export declare const Range: Story;
export declare const TimePicker: Story;
export declare const WithMinDate: Story;
export declare const WithMaxDate: Story;
export declare const DisableDate: Story;
export declare const DisableByFunction: Story;
export declare const Valid: Story;
export declare const Invalid: Story;
export declare const WithErrortext: Story;
export declare const WithSuccesstext: Story;
export declare const WithHelptex: Story;
export declare const InvalidPreload: Story;
export declare const ControlledDateTimePicker: Story;
//# sourceMappingURL=DateTimePicker.stories.d.ts.map