apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    dns-manager: "true"
    dns-manager/zone-name: "{{ .Values.global.region }}.cloud.sap"
    kubernetes.io/tls-acme: "true"
  labels:
    app: juno
  name: juno
  namespace: juno
spec:
  rules:
    - host: "juno.{{ .Values.global.region }}.cloud.sap"
      http:
        paths:
          - backend:
              serviceName: juno
              servicePort: 5000
            path: /            
{{- if eq .Values.global.region "eu-nl-1" }}
    - host: "juno.global.cloud.sap"
      http:
        paths:
          - backend:
              serviceName: juno
              servicePort: 5000
            path: /
{{- end }} 

  tls:
    - hosts: 
        - "juno.{{ .Values.global.region }}.cloud.sap"
{{- if eq .Values.global.region "eu-nl-1" }}      
        - "juno.global.cloud.sap"
{{- end }}        
      secretName: "tls-juno-{{ .Values.global.region }}-cloud-sap"
