apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    dns-manager: "true"
    dns-manager/zone-name: "{{ .Values.global.region }}.cloud.sap"
    kubernetes.io/tls-acme: "true"
  # labels:
  #   app: juno
  name: juno
  namespace: juno
spec:
  rules:
    - host: "juno.{{ .Values.global.region }}.cloud.sap"
      http:
        paths:
          - backend:
              serviceName: juno-dashboard
              servicePort: 5000
            path: / 

          - backend:
              serviceName: juno-cdn
              servicePort: 8888
            path: /cdn                       
{{- if eq .Values.global.region "eu-nl-1" }}
    - host: "juno.global.cloud.sap"
      http:
        paths:
          - backend:
              serviceName: juno-dashboard
              servicePort: 5000
            path: /
          - backend:
              serviceName: juno-cdn
              servicePort: 5000
            path: /cdn  
{{- end }} 

  tls:
    - hosts: 
        - "juno.{{ .Values.global.region }}.cloud.sap"
{{- if eq .Values.global.region "eu-nl-1" }}      
        - "juno.global.cloud.sap"
{{- end }}        
      secretName: "tls-juno-{{ .Values.global.region }}-cloud-sap"
