/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as ServicesImport } from "./routes/services"
import { Route as IndexImport } from "./routes/index"
import { Route as ServicesServiceImport } from "./routes/services_.$service"

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const ServicesServiceRoute = ServicesServiceImport.update({
  id: "/services_/$service",
  path: "/services/$service",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/services": {
      id: "/services"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    "/services_/$service": {
      id: "/services_/$service"
      path: "/services/$service"
      fullPath: "/services/$service"
      preLoaderRoute: typeof ServicesServiceImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/services": typeof ServicesRoute
  "/services/$service": typeof ServicesServiceRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/services": typeof ServicesRoute
  "/services/$service": typeof ServicesServiceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/services": typeof ServicesRoute
  "/services_/$service": typeof ServicesServiceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/services" | "/services/$service"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/services" | "/services/$service"
  id: "__root__" | "/" | "/services" | "/services_/$service"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  ServicesServiceRoute: ServicesServiceRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/services",
        "/services_/$service"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/services_/$service": {
      "filePath": "services_.$service.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
