/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SilencesImport } from './routes/silences'
import { Route as AlertsImport } from './routes/alerts'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SilencesRoute = SilencesImport.update({
  id: '/silences',
  path: '/silences',
  getParentRoute: () => rootRoute,
} as any)

const AlertsRoute = AlertsImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsImport
      parentRoute: typeof rootRoute
    }
    '/silences': {
      id: '/silences'
      path: '/silences'
      fullPath: '/silences'
      preLoaderRoute: typeof SilencesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/silences': typeof SilencesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/silences': typeof SilencesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/silences': typeof SilencesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/silences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/silences'
  id: '__root__' | '/' | '/alerts' | '/silences'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  SilencesRoute: typeof SilencesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  SilencesRoute: SilencesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/alerts",
        "/silences"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/alerts": {
      "filePath": "alerts.tsx"
    },
    "/silences": {
      "filePath": "silences.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
