import { Button } from './index';
import { Meta, StoryObj } from '@storybook/react-vite';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Subdued: Story;
export declare const Primary: Story;
export declare const PrimaryDanger: Story;
export declare const DefaultSize: Story;
export declare const Small: Story;
export declare const XS: Story;
export declare const Disabled: Story;
export declare const SubduedDisabled: Story;
export declare const PrimaryDisabled: Story;
export declare const PrimaryDangerDisabled: Story;
export declare const DefaultWithIcon: Story;
export declare const SubduedWithIcon: Story;
export declare const SmallWithIcon: Story;
export declare const XSWithIcon: Story;
export declare const IconOnlyButton: Story;
export declare const IconOnlyAsChild: Story;
export declare const LinkAsButton: Story;
export declare const LinkAsButtonWithIcon: Story;
export declare const DefaultButtonInProgress: Story;
export declare const IconButtonInProgress: Story;
export declare const DefaultButtonInProgressWithProgressLabel: Story;
export declare const SubduedButtonInProgress: Story;
export declare const PrimaryButtonWithIconInProgress: Story;
export declare const PrimaryDangerButtonInProgress: Story;
export declare const LinkAsButtonInProgress: Story;
export declare const LinkAsButtonWithIconInProgress: Story;
export declare const DisabledInProgress: Story;
export declare const PrimaryDisabledInProgress: Story;
export declare const PrimaryDangerDisabledInProgress: Story;
export declare const SmallInProgress: Story;
export declare const XSInProgress: Story;
//# sourceMappingURL=Button.stories.d.ts.map