name: Juno (build & deploy)

on:
  push:
    branches:
      - main
    paths:
      - "apps/exampleapp/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # On release creation
  # release:
  #   types: [created]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "apps/exampleapp"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./apps/exampleapp
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          # @octocat:registry=https://npm.pkg.github.com
          # always-auth=true
          registry-url: https://npm.pkg.github.com/
          # Defaults to the user or organization that owns the workflow file
          scope: ${{ github.actor }}
      - name: build libs
        run: |
          npm --prefix ../../ install
          npm --prefix ../../ run build-libs

      - name: Clean install of all existing dependencies
        run: |
          npm ci
          echo "===================="
          ls -la
          echo "===================="
          ls -la ../../
          echo "===================="

      # - name: Build app
      #   run: npm run build

      - name: Publish to github packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
