name: "Slack Notification"
description: "Send a Slack notification"
inputs:
  title:
    description: "Title for the Slack notification"
    required: true
  body:
    description: "Body of the Slack notification"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send a Slack notification if a publish happens
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://raw.githubusercontent.com/cloudoperators/juno/main/assets/logos/JUNO_logo_slack.png",
                    "alt_text": "cloudoperators/juno"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ inputs.title }}"
                  }
                ]
              },
              {
                "type": "rich_text",
                "elements": [
                  {
                    "type": "rich_text_preformatted",
                    "elements": [
                      {
                        "type": "text",
                        "text": "${{ inputs.body }}"
                      }
                    ],
                    "border": 0
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
