name: Slack Notification

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: [default]
    steps:
      - name: Send a Slack notification if a publish happens
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://raw.githubusercontent.com/cloudoperators/juno/main/assets/logos/JUNO_logo_slack.png",
                      "alt_text": "cloudoperators/juno"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "JUNO ${{ inputs.title }}"
                    }
                  ]
                },
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_preformatted",
                      "elements": [
                        {
                          "type": "text",
                          "text": ${{ inputs.body }}
                        }
                      ],
                      "border": 0
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
