name: test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write

jobs:
  test:
    runs-on: [default]
    steps:
      - name: Generate filters
        id: generate-filters
        run: |
          echo "Success"

  notify-on-success:
    needs: [test] # List the jobs that should complete successfully
    uses: cloudoperators/juno/.github/workflows/shared-slack-notification.yaml@main
    with:
      title: "Testing rich BODY! 🚀"
      body: '[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]'
      rich_body: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
