name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build-and-push:
    name: Build and Push Some Image
    runs-on: [default]
    outputs:
      failed: ${{ steps.set-failure-output.outputs.failed }}

    steps:
      - name: produce an error
        run: exit 1
      - name: Set failure output
        id: set-failure-output
        if: failure()
        run: echo "failed=build-and-push" >> $GITHUB_OUTPUT

  vulnerability-scan:
    name: Build and Push Some Image
    runs-on: [default]
    outputs:
      failed: ${{ steps.set-failure-output.outputs.failed }}

    steps:
      - name: produce an error
        run: exit 1
      - name: Set failure output
        id: set-failure-output
        if: failure()
        run: echo "failed=vulnerability-scan" >> $GITHUB_OUTPUT

  notify-on-failure:
    if: failure()
    permissions:
      contents: read
    needs: [build-and-push, vulnerability-scan]
    uses: cloudoperators/juno/.github/workflows/shared-slack-notification.yaml@main
    with:
      title: "🚨 TESTING WORKFLOW WITH FAILING JOB NAME 🚨"
      body: |
        An error occurred while building the Greenhouse image for the branch `${{ github.head_ref || github.ref_name }}`.

        ❌ Failing jobs:
        - ${{ needs.build-and-push.outputs.failed }}
        - ${{ needs.vulnerability-scan.outputs.failed }}

        <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Check the logs>
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
