# Run it locally with act
#  1. Install act:
#     `brew install act`
#  2. Create a .secret file with the following content:
#     `GITHUB_TOKEN=your_github_token`
# WORKFLOW CALL
# 1.Create a act_workflow_call.json file with the following content:
#     `{"inputs": {"path": "packages/communicator", "node": "20.x"}}`
# 2. Run the following command:
#     `act workflow_call --eventpath act_workflow_call_test_build.json --container-architecture linux/amd64 -P default=catthehacker/ubuntu:act-latest -j test-unit-build`

name: Unit Test and Build Package

on:
  workflow_call:
    inputs:
      path:
        description: "Path to the npm package"
        required: true
        type: string
      node:
        description: "Node version to use"
        required: true
        type: string

jobs:
  test-unit-build:
    runs-on: [ubutnu-latest]
    defaults:
      run:
        working-directory: ${{ inputs.path }} # Set the working directory for all steps in this job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Inputs
        run: |
          echo "====${{ github.workflow }} Inputs===="
          echo "Inputs: ${{ toJson(inputs) }}"
          echo "===="

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}

      - name: Run clean install to ensure existing package-lock.json and dependencies in the package lock match those in package.json
        run: |
          npm ci

      - name: Run unit tests for the package
        run: |
          npm i
          npm run test

      - name: Build package if script is available
        run: |
          if jq -e '.scripts.build' package.json > /dev/null; then
            npm run build
          else
            echo "=== Build script not found in package.json ==="
          fi
