# Run it locally with act (https://github.com/nektos/act)
#  1. Install act:
#     `brew install act`
#  2. Create a .secret file with the following content:
#     `GITHUB_TOKEN=your_github_token`
#  PULL REQUEST
#  1. Create a act_pull_request.json file in case of a pull request with the following content:
#     `{"pull_request": {"number": <PR number>, "head": {"ref": "<PR branch name>", "sha": "PR commit sha"}, "base": {"ref": "main"}}, "repository": {"name": "juno", "owner": {"login": "cloudoperators"}}}`
#  2. Run the following command:
#     `act push -e act_push.json -W .github/workflows/deploy-github-pages.yaml`
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "libs/**"
      - "apps/**"

jobs:
  run-detect-changes:
    uses: cloudoperators/juno/.github/workflows/check-changes-npm-package.yaml@main
    with:
      paths: "apps libs"

  run-pipeline:
    needs: [run-detect-changes]
    strategy:
      matrix:
        change: ${{fromJson(needs.run-detect-changes.outputs.changes)}}
        node: [20.x]
      fail-fast: false # Allow other jobs to continue if one fails
    uses: cloudoperators/juno/.github/workflows/publish-npm-package-npm.yaml@main
    with:
      path: ${{ matrix.change }}
      node: "${{ matrix.node }}"
