/*
 * SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Juno contributors
 * SPDX-License-Identifier: Apache-2.0
 */

// opacity helper to make custom colors work with opacity
// function withOpacity(variableName){
//   return ({ opacityVariable, opacityValue }) => {
//     if (opacityValue !== undefined) {
//       return `rgba(var(${variableName}), ${opacityValue})`
//     }
//     if (opacityVariable !== undefined) {
//       return `rgba(var(${variableName}), var(${opacityVariable}, 1))`
//     }
//     return `rgb(var(${variableName}))`
//   }
// }



module.exports = {
  content: [
    "./src/components/**/*.{js,jsx,ts,tsx,mdx}",
    "./src/dummyComponents/*.{js,jsx,ts,tsx,mdx}",
    "./src/docs/**/*.{js,jsx,ts,tsx,mdx}",
  ],
  prefix: "jn-",
  theme: {
    fontFamily: {
      sans: ['"IBM Plex Sans"', "ui-sans-serif", "Arial", "system-ui", "sans-serif"],
      condensed: ['"IBM Plex Sans Condensed"', "ui-sans-serif", "Arial", "system-ui", "sans-serif"],
      serif: ['"IBM Plex Serif"', "ui-serif", "serif"],
      mono: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
    },
    colors: {
      current: "currentColor", // this is required for fill-current and stroke-current to work when you have custom colors
      "juno-grey-blue": {
        1: "var(--color-juno-grey-blue-1-raw)",
        2: "var(--color-juno-grey-blue-2-raw)",
        3: "var(--color-juno-grey-blue-3-raw)",
        4: "var(--color-juno-grey-blue-4-raw)",
        5: "var(--color-juno-grey-blue-5-raw)",
        6: "var(--color-juno-grey-blue-6-raw)",
        7: "var(--color-juno-grey-blue-7-raw)",
        8: "var(--color-juno-grey-blue-8-raw)",
        9: "var(--color-juno-grey-blue-9-raw)",
        10: "var(--color-juno-grey-blue-10-raw)",
        11: "var(--color-juno-grey-blue-11-raw)",
        DEFAULT: "var(--color-juno-grey-blue-11-raw)",
      },
      "juno-blue": {
        1: "var(--color-juno-blue-1-raw)",
        2: "var(--color-juno-blue-2-raw)",
        3: "var(--color-juno-blue-3-raw)",
        4: "var(--color-juno-blue-4-raw)",
        5: "var(--color-juno-blue-5-raw)",
        6: "var(--color-juno-blue-6-raw)",
        7: "var(--color-juno-blue-7-raw)",
        8: "var(--color-juno-blue-8-raw)",
        9: "var(--color-juno-blue-9-raw)",
        10: "var(--color-juno-blue-10-raw)",
        DEFAULT: "var(--color-juno-blue-5-raw)",
      },
      "juno-turquoise": {
        1: "var(--color-juno-turquoise-1-raw)",
        2: "var(--color-juno-turquoise-2-raw)",
        3: "var(--color-juno-turquoise-3-raw)",
        4: "var(--color-juno-turquoise-4-raw)",
        5: "var(--color-juno-turquoise-5-raw)",
        6: "var(--color-juno-turquoise-6-raw)",
        7: "var(--color-juno-turquoise-7-raw)",
        8: "var(--color-juno-turquoise-8-raw)",
        9: "var(--color-juno-turquoise-9-raw)",
        10: "var(--color-juno-turquoise-10-raw)",
        DEFAULT: "var(--color-juno-turquoise-5-raw)",
      },
      "juno-grey-light": {
        1: "var(--color-juno-grey-light-1-raw)",
        2: "var(--color-juno-grey-light-2-raw)",
        3: "var(--color-juno-grey-light-3-raw)",
        4: "var(--color-juno-grey-light-4-raw)",
        5: "var(--color-juno-grey-light-5-raw)",
        6: "var(--color-juno-grey-light-6-raw)",
        7: "var(--color-juno-grey-light-7-raw)",
        8: "var(--color-juno-grey-light-8-raw)",
        9: "var(--color-juno-grey-light-9-raw)",
        10: "var(--color-juno-grey-light-10-raw)",
        11: "var(--color-juno-grey-light-11-raw)",
        DEFAULT: "var(--color-juno-grey-light-1-raw)",
      },
      "juno-red": {
        1: "var(--color-juno-red-1-raw)",
        2: "var(--color-juno-red-2-raw)",
        3: "var(--color-juno-red-3-raw)",
        4: "var(--color-juno-red-4-raw)",
        5: "var(--color-juno-red-5-raw)",
        6: "var(--color-juno-red-6-raw)",
        7: "var(--color-juno-red-7-raw)",
        8: "var(--color-juno-red-8-raw)",
        DEFAULT: "var(--color-juno-red-5-raw)",
      },
      "sap-grey": {
        1: "var(--color-sap-grey-1-raw)",
        2: "var(--color-sap-grey-2-raw)",
        3: "var(--color-sap-grey-3-raw)",
        4: "var(--color-sap-grey-4-raw)",
        5: "var(--color-sap-grey-5-raw)",
        6: "var(--color-sap-grey-6-raw)",
        7: "var(--color-sap-grey-7-raw)",
        8: "var(--color-sap-grey-8-raw)",
        DEFAULT: "var(--color-sap-grey-8-raw)",
      },
      "sap-blue": {
        1: "var(--color-sap-blue-1-raw)",
        2: "var(--color-sap-blue-2-raw)",
        3: "var(--color-sap-blue-3-raw)",
        4: "var(--color-sap-blue-4-raw)",
        5: "var(--color-sap-blue-5-raw)",
        6: "var(--color-sap-blue-6-raw)",
        DEFAULT: "var(--color-sap-blue-5-raw)",
      },
      "sap-gold": {
        DEFAULT: "var(--color-sap-gold-raw)",
      },
      "sap-purple": {
        1: "var(--color-sap-purple-1-raw)",
        2: "var(--color-sap-purple-2-raw)",
        3: "var(--color-sap-purple-3-raw)",
        4: "var(--color-sap-purple-4-raw)",
        5: "var(--color-sap-purple-5-raw)",
        6: "var(--color-sap-purple-6-raw)",
        DEFAULT: "var(--color-sap-purple-5-raw)",
      },
      "sap-green": {
        1: "var(--color-sap-green-1-raw)",
        2: "var(--color-sap-green-2-raw)",
        3: "var(--color-sap-green-3-raw)",
        4: "var(--color-sap-green-4-raw)",
        5: "var(--color-sap-green-5-raw)",
        6: "var(--color-sap-green-6-raw)",
        DEFAULT: "var(--color-sap-green-5-raw)",
      },
      "sap-orange": {
        1: "var(--color-sap-orange-1-raw)",
        2: "var(--color-sap-orange-2-raw)",
        3: "var(--color-sap-orange-3-raw)",
        4: "var(--color-sap-orange-4-raw)",
        5: "var(--color-sap-orange-5-raw)",
        6: "var(--color-sap-orange-6-raw)",
        DEFAULT: "var(--color-sap-orange-5-raw)",
      },
      white: "var(--color-white-raw)",
      black: "var(--color-black-raw)",
      transparent: "transparent",
      theme: {
        accent: "var(--color-accent-raw)",
        danger: "var(--color-danger-raw)",
        error: "var(--color-error-raw)",
        info: "var(--color-info-raw)",
        success: "var(--color-success-raw)",
        warning: "var(--color-warning-raw)",
        focus: "var(--color-focus-raw)",
        "background-lvl-0": "var(--color-background-lvl-0-raw)",
        "background-lvl-1": "var(--color-background-lvl-1-raw)",
        "background-lvl-2": "var(--color-background-lvl-2-raw)",
        "background-lvl-3": "var(--color-background-lvl-3-raw)",
        "background-lvl-4": "var(--color-background-lvl-4-raw)",
        "background-lvl-5": "var(--color-background-lvl-5-raw)",
      },
    },
    extend: {
      backgroundColor: {
        theme: {
          "global-bg": "var(--color-global-bg-raw)",
          "badge-default": "var(--color-badge-default-bg)",
          "box-default": "var(--color-box-bg)",
          "code-block": "var(--color-codeblock-bg)",
          "content-area-bg": "var(--color-content-area-bg-raw)",
          panel: "var(--color-panel-bg)",
          textinput: "var(--color-textinput-bg)",
          "textinput-autofill": "var(--color-textinput-autofill-bg)",
          select: "var(--color-select-bg)",
          checkbox: "var(--color-checkbox-bg)",
          radio: "var(--color-radio-bg)",
          "radio-checked": "var(--color-radio-checked-bg)",
          "switch-handle": "var(--color-switch-handle-bg)",
          "switch-handle-checked": "var(--color-switch-handle-checked-bg)",
          required: "var(--color-required-bg)",
          introbox: "var(--color-introbox-bg)",
          "datagridrow-selected": "var(--color-datagridrow-selected)",
          "datalistrow-selected": "var(--color-datalistrow-selected)",
          "message-border-danger": "var(--color-message-danger-border)",
          "message-border-default": "var(--color-message-default-border)",
          "message-border-error": "var(--color-message-error-border)",
          "message-border-warning": "var(--color-message-warning-border)",
          "message-border-success": "var(--color-message-success-border)",
          "tab-navigation-top": "var(--color-tabnavigation-top-bg)",
          filters: "var(--color-filters-bg)",
          "filter-input": "var(--color-filter-input-bg)",
          "filter-input-textinput": "var(--color-filter-input-textinput-bg)",
          "filter-pill-key": "var(--color-filter-pill-key-bg)",
          "modal-backdrop": "var(--color-modal-backdrop-bg)",
          "sidenavigation-item-active": "var(--color-sidenavigation-item-active-bg)",
          "topnavigation-item": "var(--color-topnavigation-item-bg)",
          "topnavigation-item-active": "var(--color-topnavigation-item-active-bg)",
        },
      },
      backgroundImage: {
        "theme-message-default": "var(--gradient-message-default-bg)",
        "theme-message-success": "var(--gradient-message-success-bg)",
        "theme-message-warning": "var(--gradient-message-warning-bg)",
        "theme-message-danger": "var(--gradient-message-danger-bg)",
        "theme-message-error": "var(--gradient-message-error-bg)",
      },
      textColor: {
        theme: {
          highest: "var(--color-text-highest-raw)",
          high: "var(--color-text-high-raw)",
          default: "var(--color-text-default-raw)",
          light: "var(--color-text-light-raw)",
          disabled: "var(--color-text-disabled-raw)",
          link: "var(--color-text-link-raw)",
          "on-danger": "var(--color-button-danger-text)",
          "on-default": "var(--color-button-default-text)",
          textinput: "var(--color-textinput-text)",
          "textinput-autofill": "var(--color-textinput-autofill-text)",
          "textinput-autofill-label": "var(--color-textinput-autofill-label)",
          "checkbox-checked": "var(--color-checkbox-checked-color)",
          "sidenavigation-item-active": "var(--color-sidenavigation-item-active)",
        },
      },
      borderColor: {
        theme: {
          default: "var(--color-default-border)",
          "codeblock-bar": "var(--color-codeblock-bar-border)",
          "codeblock-tab-active": "var(--color-text-default-raw)",
          "message-default": "var(--color-message-default-border)",
          "message-danger": "var(--color-message-danger-border)",
          "message-error": "var(--color-message-error-border)",
          "message-warning": "var(--color-message-warning-border)",
          "message-success": "var(--color-message-success-border)",
          panel: "var(--color-panel-border-raw)",
          "switch-default": "var(--color-switch-default-border)",
          "switch-hover": "var(--color-switch-hover-border)",
          "datalist-row": "var(--color-datalist-row-border)",
          introbox: "var(--color-introbox-border)",
          "tab-navigation-content-bottom": "var(--color-tabnavigation-content-bottom-border)",
          "tab-active-bottom": "var(--color-text-default-raw)",
          "filter-input": "var(--color-filter-input-border)",
          "filter-pill": "var(--color-filter-pill-border)",
          "box-default": "var(--color-box-border)",
          "textinput-default": "var(--color-textinput-default-border)",
          "tab-content-inactive-bottom": "var(--color-background-lvl-4-raw)",
        },
      },
      // backgroundImage: theme => ({
      //   'icon-arrow-down': "url('./img/icon_arrow_down.svg')",
      // }),
      padding: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        "grid-column": "0 .5rem",
      },
      height: {
        textinput: "2.375rem",
        floatinglabelinput: "3rem",
        "switch-default": "1.4375rem",
        "switch-handle-default": "1.1875rem",
      },
      ringOffsetColor: {
        theme: {
          focus: "var(--color-global-bg-raw)",
        },
      },
      screens: {
        "3xl": "1856px",
      },
      width: {
        "switch-default": "2.625rem",
        "switch-handle-default": "1.1875rem",
        "grid-column-default": "var(--grid-column-default-width)",
        "grid-col-1": "8.333333%",
        "grid-col-2": "16.666667%",
        "grid-col-3": "25%",
        "grid-col-4": "33.333333%",
        "grid-col-5": "41.666667%",
        "grid-col-6": "50%",
        "grid-col-7": "58.333333%",
        "grid-col-8": "66.666667%",
        "grid-col-9": "75%",
        "grid-col-10": "83.333333%",
        "grid-col-11": "91.666667%",
        "grid-col-12": "100%",
      },
      borderRadius: {
        "3px": "3px",
      },
      margin: {
        "grid-row": "0 var(--grid-row-margin-x)",
      },
      flex: {
        "grid-column": "var(--grid-column-flex-grow) var(--grid-column-flex-shrink) var(--grid-column-flex-basis)",
      },
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
    },
  },
  plugins: [],
}
